name: Deploy Blazor WebAssembly to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release "Converter Web Application/Converter Web Application.csproj"

      - name: Publish with dotnet
        run: dotnet publish --configuration Release --output ./publish "Converter Web Application/Converter Web Application.csproj"

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'converter-web-app'
          slot-name: 'Production'
          package: ./publish
